//this file is generated by perl script mkurom.
//Do not edit under pain of losing your edits!
 
module ID__ 
 #(ua=4)
( 
      input logic [5:0] IR,
      output logic [ua-1:0] Uip 
            ); 
always_comb begin
  unique casex (IR) 
    6'b00_00_00 :  Uip = 6'd5 ;   // HALT 
    6'b00_00_01 :  Uip = 6'd6 ;   // NOP 
    6'b11_10_?? :  Uip = 6'd7 ;   // LOADI 
    6'b10_11_?? :  Uip = 6'd12 ;   // STORE 
    6'b10_10_?? :  Uip = 6'd19 ;   // LOAD 
    6'b00_00_11 :  Uip = 6'd26 ;   // JUMP 
    6'b00_00_10 :  Uip = 6'd30 ;   // LOADBPR 
    6'b00_01_0? :  Uip = 6'd35 ;   // SETPG 
    default:      Uip = 6'd4 ;   // #UD fault 
  endcase
end
endmodule  // ID__ 
